#!/usr/bin/env python3

# Standard library imports
from random import randint, choice as rc

# Remote library imports
from faker import Faker

# Local imports
from app import app
from models import db, Book, Author, Genre, Review, BookAuthor

if __name__ == '__main__':
    fake = Faker()
    with app.app_context():
        Book.query.delete()
        Author.query.delete()
        Genre.query.delete()
        Review.query.delete()
        print("Starting seed...") 

        author1 = Author(name="Gabrielle Zevin", image="/assets/authors/zevin.webp", bio="Gabrielle Zevin is a New York Times best-selling novelist whose books have been translated into forty languages.")
        author2 = Author(name="Mia Sheridan", image="/assets/authors/mia.webp", bio="Mia Sheridan is a New York Times, USA Today, and Wall Street Journal bestselling author. Her passion is weaving true love stories about people destined to be together. Mia lives in Cincinnati, Ohio with her husband. They have four children here on earth and one in heaven.")
        author3 = Author(name="Sarah J. Maas", image="/assets/authors/maas.jpeg", bio="Sarah Janet Maas is an American fantasy author known for her fantasy series Throne of Glass, A Court of Thorns and Roses, and Crescent City. As of 2022, she has sold over twelve million copies of her books and her work has been translated into 37 languages.")
        author4 =  Author(name="Lois Lowry", image="/assets/authors/lois.jpeg", bio="Lois Lowry (born March 20, 1937, Honolulu, Hawaii) American author who wrote some 50 books, mainly directed toward young adults, beginning in the 1970s. By the early 1990s she had solidified her reputation by winning two Newbery Medals, awarded for the most distinguished children’s book of the year. On her website, Lowry described the major themes of her books: “I try, through writing, to convey my passionate awareness that we live intertwined on this planet and that our future depends upon our caring more, and doing more, for one another.")
        author5 =  Author(name="Abraham Verghese", image="/assets/authors/abraham.jpeg", bio="Abraham Verghese, MD, MACP, is Professor and Linda R. Meier and Joan F. Lane Provostial Professor, and Vice Chair for the Theory and Practice of Medicine at the School of Medicine at Stanford University. He is also a best-selling author and a physician with a reputation for his focus on healing in an era where technology often overwhelms the human side of medicine. He received the Heinz Award in 2014 and was awarded the National Humanities Medal, presented by President Barack Obama, in 2015.")
        author6 =  Author(name="Hanya Yanagihara", image="/assets/authors/hanya.webp", bio="Hanya Yanagihara is an American novelist, editor, and travel writer. She grew up in Hawaii. She is best known for her bestselling novel A Little Life, which was shortlisted for the 2015 Booker Prize, and for being the editor-in-chief of T Magazine.")
        author7 =  Author(name="Rebecca Yarros", image="/assets/authors/yarros.jpeg", bio="Rebecca Yarros is an American author. She is best known for the Empyrean fantasy book series, which will be adapted into a television series with Amazon; Yarros will serve as a non-writing executive producer. Yarros graduated from Troy University, where she studied European history and English.")
        author8 = Author(name="Emily Henry", image="/assets/authors/emily.jpeg", bio="Emily Henry is the #1 New York Times and #1 sunday times bestselling author of happy place, book lovers, people we meet on vacation, and beach read, as well as the forthcoming funny story. she lives and writes in the american midwest.")
        author9 = Author(name="Kristin Hannah", image="/assets/authors/kristin.webp", bio="Kristin Hannah is the award-winning and bestselling author of more than 20 novels including the international blockbuster, The Nightingale, which was named Goodreads Best Historical fiction novel for 2015 and won the coveted People’s Choice award for best fiction in the same year.  Additionally, it was a selection of the Reese Witherspoon Book Club in 2023. It was named a Best Book of the Year by Amazon, iTunes, Buzzfeed, the Wall Street Journal, Paste, and The Week.  In 2018, The Great Alone became an instant New York Times #1 bestseller and was named the Best Historical Novel of the Year by Goodreads.")
        author10 = Author(name="Bessel van der Kolk", image="/assets/authors/bessel.webp", bio="Bessel van der Kolk is a Dutch psychiatrist, author, researcher and educator. Since the 1970s his research has been in the area of post-traumatic stress. He is the author of The New York Times best seller, The Body Keeps the Score. ")
        author11 = Author(name="David Baldacci", image="/assets/authors/david.jpeg", bio="David published his first novel, Absolute Power, in 1996. The feature film adaptation followed, with Clint Eastwood as its director and star. In total, David has published 49 novels for adults; all have been national and international bestsellers, and several have been adapted for film and television. His novels are published in over 45 languages and in more than 80 countries, with 150 million copies sold worldwide. David has also published seven novels for young readers.")
        author12 = Author(name="Jonathan Haidt", image="/assets/authors/haidt.jpeg", bio="Jonathan David Haidt is an American social psychologist and author. He is the Thomas Cooley Professor of Ethical Leadership at the New York University Stern School of Business. His main areas of study are the psychology of morality and moral emotions")
        author13 = Author(name="Hannah Grace", image="/assets/authors/hannah.jpg", bio="Hannah Grace is an English author, writing adult contemporary romance between characters who all carry a tiny piece of her. When she’s not describing everyone’s eyes ten-thousand-times a chapter, accidentally giving multiple characters the same name, or googling American English spellings, you can find her oversharing online, or, occasionally, reading a book from her enormous TBR. Hannah is an instant #1 New York Times bestseller of Icebreaker and Wildfire and a proud parent to two dogs.")
        author14 = Author(name="Colleen Hoover", image="/assets/authors/colleen.webp", bio="Colleen Hoover is the #1 New York Times and International bestselling author of multiple novels and novellas. She lives in Texas with her husband and their three boys. She is the founder of The Bookworm Box, a non-profit book subscription service and bookstore in Sulphur Springs, Texas.")
        author15 = Author(name="Kate Canterbary", image="/assets/authors/kate.jpeg", bio="USA Today Bestseller Kate Canterbary writes smart, steamy contemporary romances loaded with heat, heart, and happy ever afters. Kate lives on the New England coast with her husband and daughter.")
        author16 = Author(name="Elle Kennedy", image="/assets/authors/elle.jpeg", bio="A New York Times, USA Today and Wall Street Journal bestselling author, Elle Kennedy grew up in the suburbs of Toronto, Ontario, and holds a B.A. in English from York University. From an early age, she knew she wanted to be a writer, and actively began pursuing that dream when she was a teenager. Elle currently writes for various publishers. She is the author of more than 50 titles of contemporary romance and romantic suspense novels, including the global sensation Off-Campus series.")
        author17 = Author(name="Matt Haig", image="/assets/authors/matt.jpeg", bio="Matt Haig is the author of novels such as The Midnight Library, How to Stop Time, The Humans, The Radleys, and the forthcoming The Life Impossible. He has also written books for children, such as A Boy Called Christmas, and the memoir Reasons to Stay Alive.")
        author18 = Author(name="Holly Black", image="/assets/authors/holly.jpeg", bio="Holly Black is the #1 New York Times bestselling author of over thirty fantasy novels for kids and teens. She has been a finalist for an Eisner Award and the Lodestar Award, and the recipient of the Mythopoeic Award, a Nebula, and a Newbery Honor. Her books have been translated into 32 languages worldwide and adapted for film. She currently lives in New England with her husband and son in a house with a secret library.")
        author19 = Author(name="Lauren Roberts", image="/assets/books/roverts.jpeg", bio="When Lauren Roberts isn't writing about fantasy worlds and bantering love interests, she can likely be found burrowed in bed reading about them. Lauren has lived in Michigan her whole life, which makes her very familiar with potholes, snow, and various lake activities. She has the hobbies of both a grandmother and a child: knitting, laser tag, hammocking, word searches, and coloring. Powerless is her first novel (now a New York Times Best Seller), and she hopes to have the privilege of writing pretty words for the rest of her life. If you enjoy ranting, reading, and writing, Lauren can be found on both TikTok and Instagram @Laurenrobertslibrary for your entertainment.")
        author20 = Author(name="Freida McFadden", image="/assets/authors/freida.jpeg", bio="#1 New York Times, Amazon Charts, USA Today, Wall Street Journal, Sunday Times, and Publisher's Weekly bestselling author Freida McFadden is a practicing physician specializing in brain injury who has penned multiple bestselling psychological thrillers and medical humor novels. Freida’s work has been selected as one of Amazon Editors’ best books of the year, she is the winner of the International Thriller Writers Award for best paperback, and she is a Goodreads Choice Award winner. Her novels have been translated into 40 languages.")
        author21 = Author(name="R.F. Kuang", image="/assets/authors/kuang.jpeg", bio="Rebecca F. Kuang is the award-winning, #1 New York Times bestselling author of the Poppy War trilogy, Babel: An Arcane History, and Yellowface. She has an MPhil in Chinese Studies from Cambridge and an MSc in Contemporary Chinese Studies from Oxford; she is now pursuing a PhD in East Asian Languages and Literatures at Yale.")
        author22 = Author(name="Harper Lee", image="/assets/authors/harper.jpeg", bio="elle Harper Lee was an American novelist whose 1960 novel To Kill a Mockingbird won the 1961 Pulitzer Prize and became a classic of modern American literature. She assisted her close friend Truman Capote in his research for the book In Cold Blood.")
        author23 = Author(name="Salman Rushdie", image="/assets/authors/salman.webp", bio="The Satanic Verses (1988), novel of Indian-born British writer Salman Rushdie led Ruholla Khomeini, the ayatollah of Iran, to demand his execution and then forced him into hiding; his other works include Midnight's Children (1981), which won the Booker prize, and The Moor's Last Sigh (1995). Sir Ahmed Salman Rushdie, a novelist and essayist, set much of his early fiction at least partly on the Indian subcontinent. His style is often classified as magical realism, while a dominant theme of his work is the story of the many connections, disruptions and migrations between the Eastern and Western world.")
        author24 = Author(name="Jennette McCurdy", image="/assets/authors/mccurdy.jpg", bio="Jennette McCurdy got her start in child acting, which by her late teen years had brought her success (she starred in Nickelodeon's hit show iCarly and her own spin-off, Sam & Cat). She went on to star in the Netflix series Between, and had a short-lived country music career with Capitol Records Nashville. Despite her outside success, McCurdy felt ashamed of 90% of her resume and ultimately unfulfilled, so she turned to alcohol, but since that didn't work, she quit acting and began pursuing writing/directing in 2017. She has written/directed a pilot and four short films. Her work has been featured in/on The Hollywood Reporter, Short of the Week, Florida Film Festival, Salute Your Shorts, and many more. She has written articles for Huffington Post and the Wall Street Journal. Her one-woman show “I’m Glad My Mom Died” had a sold-out run at Lyric Hyperion Theatre. She hosts a podcast called “Empty Inside”, where she speaks with guests about uncomfortable topics.")
        author25 = Author(name="Malcolm Gladwell", image="/assets/authors/gladwell.jpg", bio="Malcolm Timothy Gladwell CM is a Canadian journalist, author, and public speaker. He has been a staff writer for The New Yorker since 1996. He has published seven books. He is also the host of the podcast Revisionist History and co-founder of the podcast company Pushkin Industries.")
        author26 = Author(name="Doris Kearns Goodwin", image="/assets/authors/doris.jpeg", bio="DORIS KEARNS GOODWIN’s interest in leadership began more than half a century ago as a professor at Harvard. Her experiences working for LBJ in the White House and later assisting him on his memoirs led to her bestselling 'Lyndon Johnson and the American Dream.' She followed up with the Pulitzer Prize–winning 'No Ordinary Time: Franklin & Eleanor Roosevelt: The Home Front in World War II.' She earned the Lincoln Prize for the runaway bestseller 'Team of Rivals,' the basis for Steven Spielberg’s Academy Award-winning film 'Lincoln,' and the Carnegie Medal for 'The Bully Pulpit,' the 'New York Times' bestselling chronicle of the friendship between Theodore Roosevelt and William Howard Taft. She lives in Concord, Massachusetts.")
        author27 = Author(name="Benjamin Labatut", image="/assets/authors/benjamin.webp", bio="Benjamin Labatut was born in Rotterdam, Netherlands. He spent his childhood in The Hague and Buenos Aires and when he was twelve years old he moved to Santiago de Chile, where he lives today. La Antártica empieza aquí was his first book, being published in México, where it won Premio Caza de Letras 2009, delivered by Universidad Autónoma de México (UNAM) and Editorial Alfaguara.")

    


        db.session.add_all([author1, author2, author3, author4, author5, author6, author7, author8, author9, author10, author11, author12, author13, author14, author15, author16, author17, author18, author19, author20, author21, author22, author23, author24, author25, author26, author27])
        db.session.commit() 


      # Check
        genre1 = Genre(type="Contemporary Romance")
        # Check
        genre2 = Genre(type="Fantasy")
        # Check
        genre3 = Genre(type="Fiction")
        genre4 = Genre(type="Nonfiction")
        genre5 = Genre(type="Historical Fiction")
        genre6 = Genre(type="Science Fiction")
        genre7 = Genre(type="Mystery")
        genre8 = Genre(type="Young Adult")
        genre9 = Genre(type="Self-Help")
        genre10 = Genre(type="Memoir")
        genre11 = Genre(type="Short Story")
        genre12 = Genre(type="Horror Fiction")
        genre13 = Genre(type="Crime Fiction")
        genre14 = Genre(type="Science")
        genre15 = Genre(type="Romance Novel")
        genre16 = Genre(type="Biography")
        genre17 = Genre(type="Historical Fantasy")
        genre18 = Genre(type="Thriller")

        db.session.add_all([genre1, genre2, genre3, genre4, genre5, genre6, genre7, genre8, genre9, genre10, genre11, genre12, genre13, genre14, genre15, genre16, genre17])
        db.session.commit()


        book1 = Book(title="Archer's Voice", image="/assets/books/archers-voice-cover.jpg", genre="Contemporary Romance", synopsis="Bree was looking for peace. Archer was an overlooked man dealing with trauma. One day, everything changed. Bree found the complete opposite and Archer was finally seen.", author_id=2, genre_id=1)
        book2 = Book(title="Tomorrow and Tomorrow and Tomorrow", image="/assets/books/tomorrow.jpg", genre="Coming of Age", synopsis="In love but never lovers, Sadie and Sam, go on quite the adventure through life expressing all the emotions that come with it through the builds of their video games. Peaks, valleys, and everything in between accurately depict growth that can only happen within the act of time.", author_id=1, genre_id=3)
        book3 = Book(title="A Court of Thorns and Roses", image="/assets/books/acotar.jpg", genre="Fantasy", synopsis="When nineteen-year-old huntress Feyre kills a wolf in the woods, a terrifying creature arrives to demand retribution. Dragged to a treacherous magical land she knows about only from legends, Feyre discovers that her captor is not truly a beast, but one of the lethal, immortal faeries who once ruled her world.", author_id=3, genre_id=2)
        book4 = Book(title="A Court of Mist and Fury", image="/assets/books/acomaf.jpg", genre="Fantasy", synopsis="As her marriage to Tamlin approaches, Feyre's hollowness and nightmares consume her. She finds herself split into two different one who upholds her bargain with Rhysand, High Lord of the feared Night Court, and one who lives out her life in the Spring Court with Tamlin. While Feyre navigates a dark web of politics, passion, and dazzling power, a greater evil looms. She might just be the key to stopping it, but only if she can harness her harrowing gifts, heal her fractured soul, and decide how she wishes to shape her future-and the future of a world in turmoil.", author_id=3, genre_id=2)
        book5 = Book(title="The Giver", image="/assets/books/the-giver.jpg", genre="Young Adult", synopsis="In this futuristic utopia, true emotions of happiness or pain are forbidden. Chosen from one who has experienced all, Jonas was given the power to embrace the hidden.", author_id=4, genre_id=8)
        book6 = Book(title="The Covenant of Water", image="/assets/books/water.jpg", genre="Historical Fiction", synopsis="A shimmering evocation of a bygone India and of the passage of time itself, The Covenant of Water is a hymn to progress in medicine and to human understanding, and a humbling testament to the hardships undergone by past generations for the sake of those alive today. Imbued with humor, deep emotion, and the essence of life, it is one of the most masterful literary novels published in recent years.", author_id=5, genre_id=6)
        book7 = Book(title="A Little Life", image="/assets/books/life.jpeg", genre="Fiction", synopsis="When four classmates from a small Massachusetts college move to New York to make their way, they're broke, adrift, and buoyed only by their friendship and ambition. There is kind, handsome Willem, an aspiring actor; JB, a quick-witted, sometimes cruel Brooklyn-born painter seeking entry to the art world; Malcolm, a frustrated architect at a prominent firm; and withdrawn, brilliant, enigmatic Jude, who serves as their center of gravity.", author_id=6, genre_id=3)
        book8 = Book(title="Funny Story", image="/assets/books/funny.jpeg", genre="Contemporary Romance", synopsis="Daphne always loved the way her fiancé Peter told their story. How they met (on a blustery day), fell in love (over an errant hat), and moved back to his lakeside hometown to begin their life together. He really was good at telling it…right up until the moment he realized he was actually in love with his childhood best friend  Petra.", author_id=8, genre_id=1)
        book9 = Book(title="The Women", image="/assets/books/women.jpg", genre="Historical Fiction", synopsis="Women can be heroes. When twenty-year-old nursing student Frances “Frankie” McGrath hears these words, it is a revelation. Raised in the sun-drenched, idyllic world of Southern California and sheltered by her conservative parents, she has always prided herself on doing the right thing. But in 1965, the world is changing, and she suddenly dares to imagine a different future for herself. When her brother ships out to serve in Vietnam, she joins the Army Nurse Corps and follows his path.", author_id=9, genre_id=6)
        book10 = Book(title="The Body Keeps Score", image="/assets/books/score.jpg", genre="Nonfiction", synopsis="Trauma is a fact of life. Veterans and their families deal with the painful aftermath of combat; one in five Americans has been molested; one in four grew up with alcoholics; one in three couples have engaged in physical violence. Dr. Bessel van der Kolk, one of the world's foremost experts on trauma, has spent over three decades working with survivors. In The Body Keeps the Score, he uses recent scientific advances to show how trauma literally reshapes both body and brain, compromising sufferers' capacities for pleasure, engagement, self-control, and trust. He explores innovative treatments—from neurofeedback and meditation to sports, drama, and yoga—that offer new paths to recovery by activating the brain's natural neuroplasticity. Based on Dr. van der Kolk's own research and that of other leading specialists, The Body Keeps the Score exposes the tremendous power of our relationships both to hurt and to heal—and offers new hope for reclaiming lives.", author_id=10, genre_id=4)
        book11 = Book(title="The Calamity of Souls", image="/assets/books/calamity.jpg", genre="Historical Fiction", synopsis="Set in the tumultuous year of 1968 in southern Virginia, a racially-charged murder case sets a duo of white and Black lawyers against a deeply unfair system as they work to defend their wrongfully-accused Black defendants in this courtroom drama from #1 New York Times bestselling author David Baldacci.", author_id=11, genre_id=6)
        book12 = Book(title="The Anxious Generation", image="/assets/books/generation.jpg", genre="Nonfiction", synopsis="After more than a decade of stability or improvement, the mental health of adolescents plunged in the early 2010s. Rates of depression, anxiety, self-harm, and suicide rose sharply, more than doubling on many measures. Why?", author_id=12, genre_id=4)
        book13 = Book(title="Fourth Wing", image="/assets/books/fourth.jpg", genre="Fantasy", synopsis="Twenty-year-old Violet Sorrengail was supposed to enter the Scribe Quadrant, living a quiet life among books and history. Now, the commanding general—also known as her tough-as-talons mother—has ordered Violet to join the hundreds of candidates striving to become the elite of Navarre: dragon riders.", author_id=7, genre_id=2)
        book14 = Book(title="Icebreaker", image="/assets/books/icebreaker.jpeg", genre="Contemporary Romance", synopsis="Anastasia Allen has worked her entire life for a shot at Team USA. It looks like everything is going according to plan when she gets a full scholarship to the University of California, Maple Hills and lands a place on their competitive figure skating team. Nothing will stand in her way, not even the captain of the hockey team, Nate Hawkins. Nate’s focus as team captain is on keeping his team on the ice. Which is tricky when a facilities mishap means they are forced to share a rink with the figure skating team—including Anastasia, who clearly can’t stand him. But when Anastasia’s skating partner faces an uncertain future, she may have to look to Nate to take her shot.", author_id=13, genre_id=1)
        book15 = Book(title="Wildfire", image="/assets/books/wildfire.jpeg", genre="Contemporary Romance", synopsis="The latest in the Maple Hills series follows two summer camp counselors who reconnect after a sizzling one-night stand. Maple Hills students Russ Callaghan and Aurora Roberts cross paths at a party celebrating the end of the academic year, where a drinking game results in them having a passionate one-night stand. Never one to overstay her welcome (or expect much from a man), Aurora slips away before Russ even has the chance to ask for her full name.", author_id=13, genre_id=1)
        book16 = Book(title="Daydream", image="/assets/books/daydream.jpg", genre="Contemporary Romance", synopsis="When procrastination lands him in a difficult class with his least favorite professor, Henry Turner knows he’s going to have to work extra hard to survive his junior year of college. And now with his new role as ice hockey captain – which he didn’t even want – Henry absolutely cannot fail. Enter Halle Jacobs, a fellow junior who finds herself befriended by Henry when he accidentally crashes her book club.", author_id=13, genre_id=1)
        book17 = Book(title="Maybe Someday", image="/assets/books/maybr.jpg", genre="Contemporary Romance", synopsis="At twenty-two years old, Sydney has a great life: She's in college, working a steady job, in love with her wonderful boyfriend, Hunter, and rooming with her best friend, Tori. But everything changes when she discovers Hunter's cheating on her--and she is left trying to decide what to do next. Sydney becomes captivated by Ridge, her mysterious neighbor. She can't take her eyes off him or stop listening to the passionate way he plays his guitar every evening out on his balcony. And there's something about Sydney that Ridge can't ignore, either. When their inevitable encounter happens, they soon find themselves needing each other in more ways than one...", author_id=14, genre_id=1)
        book18 = Book(title="It Ends With Us", image="/assets/books/ends.jpg", genre="Contemporary Romance", synopsis="Lily hasn’t always had it easy, but that’s never stopped her from working hard for the life she wants. She’s come a long way from the small town in Maine where she grew up — she graduated from college, moved to Boston, and started her own business. So when she feels a spark with a gorgeous neurosurgeon named Ryle Kincaid, everything in Lily’s life suddenly seems almost too good to be true. Ryle is assertive, stubborn, maybe even a little arrogant. He’s also sensitive, brilliant, and has a total soft spot for Lily. And the way he looks in scrubs certainly doesn’t hurt. Lily can’t get him out of her head. But Ryle’s complete aversion to relationships is disturbing. Even as Lily finds herself becoming the exception to his “no dating” rule, she can’t help but wonder what made him that way in the first place.", author_id=14, genre_id=1)
        book19 = Book(title="Ugly Love", image="/assets/books/ugly.jpg", genre="Contemporary Romance", synopsis="When Tate Collins meets airline pilot Miles Archer, she knows it isn’t love at first sight. They wouldn’t even go so far as to consider themselves friends. The only thing Tate and Miles have in common is an undeniable mutual attraction. Once their desires are out in the open, they realize they have the perfect set-up. He doesn’t want love, she doesn’t have time for love, so that just leaves the sex. Their arrangement could be surprisingly seamless, as long as Tate can stick to the only two rules Miles has for her. Never ask about the past. Don’t expect a future. They think they can handle it, but realize almost immediately they can’t handle it at all. Hearts get infiltrated. Promises get broken. Rules get shattered. Love gets ugly.", author_id=14, genre_id=1)
        book20 = Book(title="Underneath It All", image="/assets/books/underneath.jpeg", genre="Contemporary Romance", synopsis="Matthew Walsh doesn't have feelings, and he likes it that way. Between breathing life into his family's third generation Boston architecture shop, keeping the peace with his five siblings, and competing in triathlons, he doesn't have much time for feelings. At least that’s the case until Lauren Halsted tumbles into his life. The feisty, beautiful blonde isn’t what he wants and definitely not what he expects. She’s so much more. Lauren Halsted doesn’t have time and that’s turning into a real problem for her.", author_id=15, genre_id=1)
        book21 = Book(title="The Chase", image="/assets/books/chase.jpg", genre="Contemporary Romance", synopsis="Everyone says opposites attract. And they must be right, because there’s no logical reason why I’m so drawn to Colin Fitzgerald. I don’t usually go for tattoo-covered, video-gaming, hockey-playing nerd-jocks who think I’m flighty and superficial. His narrow view of me is the first strike against him. It doesn’t help that he’s buddy-buddy with my brother. And that his best friend has a crush on me. And that I just moved in with them. Oh, did I not mention we’re roommates?", author_id=16, genre_id=1)
        book22 = Book(title="A Court of Wings and Ruin", image="/assets/books/wings.jpg", genre="Fantasy", synopsis="IFeyre has returned to the Spring Court, determined to gather information on Tamlin's actions and learn what she can about the invading king threatening to bring her land to its knees. But to do so she must play a deadly game of deceit. One slip could bring doom not only for Feyre, but for everything-and everyone-she holds dear.", author_id=3, genre_id=2)
        book23 = Book(title="A Court of Sliver FLames", image="/assets/books/sliver.jpg", genre="Fantasy", synopsis="Nesta Archeron has always been prickly-proud, swift to anger, and slow to forgive. And ever since being forced into the Cauldron and becoming High Fae against her will, she's struggled to find a place for herself within the strange, deadly world she inhabits. Worse, she can't seem to move past the horrors of the war with Hybern and all she lost in it.", author_id=3, genre_id=2)
        book24 = Book(title="A Court of Frost and Starlight", image="/assets/books/frosy.jpeg", genre="Fantasy", synopsis="Feyre, Rhysand, and their friends are still busy rebuilding the Night Court and the vastly altered world beyond, recovering from the war that changed everything. But Winter Solstice is finally approaching, and with it, the joy of a hard-earned reprieve. Yet even the festive atmosphere can't keep the shadows of the past from looming. As Feyre navigates her first Winter Solstice as High Lady, her concern for those dearest to her deepens. They have more wounds than she anticipated-scars that will have a far-reaching impact on the future of their court.", author_id=3, genre_id=2)
        book25 = Book(title="Iron Flame", image="/assets/books/iron.jpeg", genre="Fantasy", synopsis="Everyone expected Violet Sorrengail to die during her first year at Basgiath War College—Violet included. But Threshing was only the first impossible test meant to weed out the weak-willed, the unworthy, and the unlucky. Now the real training begins, and Violet’s already wondering how she’ll get through. It’s not just that it’s grueling and maliciously brutal, or even that it’s designed to stretch the riders’ capacity for pain beyond endurance. It’s the new vice commandant, who’s made it his personal mission to teach Violet exactly how powerless she is–unless she betrays the man she loves.", author_id=7, genre_id=2)
        book26 = Book(title="The Midnight Library", image="/assets/books/midnight.jpg", genre="Fantasy", synopsis="Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. To see how things would be if you had made other choices . . . Would you have done anything different, if you had the chance to undo your regrets? A novel about all the choices that go into a life well lived.", author_id=17, genre_id=2)
        book27 = Book(title="Powerless", image="/assets/books/powerless.jpeg", genre="Fantasy", synopsis="She is the very thing he’s spent his whole life hunting. He is the very thing she’s spent her whole life pretending to be. Only the extraordinary belong in the kingdom of Ilya—the exceptional, the empowered, the Elites. The powers these Elites have possessed for decades were graciously gifted to them by the Plague, though not all were fortunate enough to both survive the sickness and reap the reward. Those born Ordinary are just that—ordinary. And when the king decreed that all Ordinaries be banished in order to preserve his Elite society, lacking an ability suddenly became a crime—making Paedyn Gray a felon by fate and a thief by necessity.", author_id=19, genre_id=2)
        book28 = Book(title="The Cruel Prince", image="/assets/books/prince.jpg", genre="Fantasy", synopsis="Jude was seven when her parents were murdered and she and her two sisters were stolen away to live in the treacherous High Court of Faerie. Ten years later, Jude wants nothing more than to belong there, despite her mortality. But many of the fey despise humans. Especially Prince Cardan, the youngest and wickedest son of the High King. To win a place at the Court, she must defy him–and face the consequences.", author_id=18, genre_id=2)
        book29 = Book(title="The Wicked King", image="/assets/books/king.jpg", genre="Fantasy", synopsis="After the jaw-dropping revelation that Oak is the heir to Faerie, Jude must keep her brother safe. To do so, she has bound the wicked king, Cardan, to her, and made herself the power behind the throne. Navigating the constantly shifting political alliances of Faerie would be difficult enough if Cardan were easy to control. But he does everything in his power to humiliate and undermine her even as his fascination with her remains undiminished", author_id=18, genre_id=2)
        book30 = Book(title="The Queen of Nothing", image="/assets/books/queen.jpg", genre="Fantasy", synopsis="Power is much easier to acquire than it is to hold onto. Jude learned this lesson when she released her control over the wicked king, Cardan, in exchange for immeasurable power. Now as the exiled mortal Queen of Faerie, Jude is powerless and left reeling from Cardan’s betrayal. She bides her time determined to reclaim everything he took from her. Opportunity arrives in the form of her deceptive twin sister, Taryn, whose mortal life is in peril. Jude must risk venturing back into the treacherous Faerie Court, and confront her lingering feelings for Cardan, if she wishes to save her sister. But Elfhame is not as she left it. War is brewing. As Jude slips deep within enemy lines she becomes ensnared in the conflict’s bloody politics.", author_id=18, genre_id=2)
        book31 = Book(title="Happy Place", image="/assets/books/happy.jpg", genre="Fiction", synopsis="Harriet and Wyn have been the perfect couple since they met in college—they go together like salt and pepper, honey and tea, lobster and rolls. Except, now—for reasons they’re still not discussing—they don’t. They broke up six months ago. And still haven’t told their best friends.", author_id=8, genre_id=3)
        book32 = Book(title="The Housemaid", image="/assets/books/housemaid.jpeg", genre="Fiction", synopsis="Every day I clean the Winchesters’ beautiful house top to bottom. I collect their daughter from school. And I cook a delicious meal for the whole family before heading up to eat alone in my tiny room on the top floor. I try to ignore how Nina makes a mess just to watch me clean it up. How she tells strange lies about her own daughter. And how her husband Andrew seems more broken every day. But as I look into Andrew’s handsome brown eyes, so full of pain, it’s hard not to imagine what it would be like to live Nina’s life. The walk-in closet, the fancy car, the perfect husband.", author_id=20, genre_id=3)
        book33 = Book(title="The Inmate", image="/assets/books/inmate.jpeg", genre="Fiction", synopsis="There are three rules Brooke Sullivan must follow as a new nurse practitioner at a men's maximum-security 1) Treat all prisoners with respect. 2) Never reveal any personal information. 3) Never EVER become too friendly with the inmates. But none of the staff at the prison knows Brooke has already broken the rules. Nobody knows about her intimate connection to Shane Nelson, one of the penitentiary's most notorious and dangerous inmates. And they certainly don't know that Shane was Brooke's high school sweetheart―the star quarterback who is now spending the rest of his life in prison for a series of grisly murders. Or that Brooke's testimony was what put him there. But Shane knows. And he will never forget.", author_id=20, genre_id=3)
        book34 = Book(title="Yellowface", image="/assets/books/yellow.jpg", genre="Fiction", synopsis="White lies. Dark humor. Deadly consequences... Bestselling sensation Juniper Song is not who she says she is, she didn't write the book she claims she wrote, and she is most certainly  not  Asian American--in this chilling and hilariously cutting novel from R.F. Kuang, the #1  New York Times  bestselling author of Babel .   Authors June Hayward and Athena Liu were supposed to be twin rising stars. But Athena's a literary darling. June Hayward is literally nobody. Who wants stories about basic white girls, June thinks. So when June witnesses Athena's death in a freak accident, she acts on she steals Athena's just-finished masterpiece, an experimental novel about the unsung contributions of Chinese laborers during World War I. So what if June edits Athena's novel and sends it to her agent as her own work? So what if she lets her new publisher rebrand her as Juniper Song--complete with an ambiguously ethnic author photo? Doesn't this piece of history deserve to be told, whoever the teller? That's what June claims, and the  New York Times  bestseller list seems to agree. But June can't get away from Athena's shadow, and emerging evidence threatens to bring June's (stolen) success down around her. As June races to protect her secret, she discovers exactly how far she will go to keep what she thinks she deserves. With its totally immersive first-person voice,  Yellowface  grapples with questions of diversity, racism, and cultural appropriation, as well as the terrifying alienation of social media. R.F. Kuang's novel is timely, razor-sharp, and eminently readable. ", author_id=21, genre_id=3)
        book35 = Book(title="To Kill A Mockingbird", image="/assets/books/kill.jpeg", genre="Fiction", synopsis="The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it. 'To Kill A Mockingbird' became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic. Compassionate, dramatic, and deeply moving, 'To Kill A Mockingbird' takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.", author_id=22, genre_id=3)
        book36 = Book(title="Good Girl Complex", image="/assets/books/complex.jpeg", genre="Fiction", synopsis="Mackenzie 'Mac' Cabot is a people pleaser. Her demanding parents. Her prep school friends. Her long-time boyfriend. It's exhausting, really, always following the rules. Unlike most twenty-year-olds, all she really wants to do is focus on growing her internet business, but first she must get a college degree at her parents' insistence. That means moving to the beachside town of Avalon Bay, a community made up of locals and the wealthy students of Garnet College.", author_id=16, genre_id=3)
        book37 = Book(title="Reminders of Him", image="/assets/books/reminders.jpg", genre="Fiction", synopsis="A troubled young mother yearns for a shot at redemption in this heartbreaking yet hopeful story from #1 New York Times bestselling author Colleen Hoover. After serving five years in prison for a tragic mistake, Kenna Rowan returns to the town where it all went wrong, hoping to reunite with her four-year-old daughter. But the bridges Kenna burned are proving impossible to rebuild. Everyone in her daughter’s life is determined to shut Kenna out, no matter how hard she works to prove herself. The only person who hasn’t closed the door on her completely is Ledger Ward, a local bar owner and one of the few remaining links to Kenna’s daughter. But if anyone were to discover how Ledger is slowly becoming an important part of Kenna’s life, both would risk losing the trust of everyone important to them. The two form a connection despite the pressure surrounding them, but as their romance grows, so does the risk. Kenna must find a way to absolve the mistakes of her past in order to build a future out of hope and healing.", author_id=14, genre_id=3)
        book38 = Book(title="The Housemaid Secret", image="/assets/books/secret.jpeg", genre="Fiction", synopsis="It's hard to find an employer who doesn't ask too many questions about my past. So I thank my lucky stars that the Garricks miraculously give me a job, cleaning their stunning penthouse with views across the city and preparing fancy meals in their shiny kitchen. I can work here for a while, stay quiet until I get what I want. It's almost perfect. But I still haven't met Mrs Garrick, or seen inside the guest bedroom. I'm sure I hear her crying. I notice spots of blood around the neck of her white nightgowns when I'm doing laundry. And one day I can't help but knock on the door. When it gently swings open, what I see inside changes everything...", author_id=20, genre_id=3)
        book39 = Book(title="The Housemaid is Watching", image="/assets/books/watching.jpg", genre="Fiction", synopsis=" I used to clean other people’s houses—now, I can’t believe this home is actually mine. The charming kitchen, the quiet cul-de-sac, the huge yard where my kids can play. My husband and I saved for years to give our children the life they deserve. Even though I’m wary of our new neighbor Mrs Lowell, when she invites us over for dinner it’s our chance to make friends. Her maid opens the door wearing a white apron, her hair in a tight bun. I know exactly what it’s like to be in her shoes. But her cold stare gives me chills…", author_id=20, genre_id=3)
        book40 = Book(title="Knife", image="/assets/books/knife.jpeg", genre="Nonfiction", synopsis="rom internationally renowned writer and Booker Prize winner Salman Rushdie, a searing, deeply personal account of enduring—and surviving—an attempt on his life thirty years after the fatwa that was ordered against him. On the morning of August 12, 2022, Salman Rushdie was standing onstage at the Chautauqua Institution, preparing to give a lecture on the importance of keeping writers safe from harm, when a man in black—black clothes, black mask—rushed down the aisle toward him, wielding a knife. His first thought: So it’s you. Here you are.", author_id=23, genre_id=4)
        book41 = Book(title="I'm Glad My Mom Died", image="/assets/books/died.jpg", genre="Nonfiction", synopsis="Jennette McCurdy was six years old when she had her first acting audition. Her mother’s dream was for her only daughter to become a star, and Jennette would do anything to make her mother happy. So she went along with what Mom called “calorie restriction,” eating little and weighing herself five times a day. She endured extensive at-home makeovers while Mom chided, “Your eyelashes are invisible, okay? You think Dakota Fanning doesn’t tint hers?” She was even showered by Mom until age sixteen while sharing her diaries, email, and all her income.", author_id=24, genre_id=4)
        book42 = Book(title="Talking To Strangers", image="/assets/books/strangers.jpg", genre="Nonfiction", synopsis="How did Fidel Castro fool the CIA for a generation? Why did Neville Chamberlain think he could trust Adolf Hitler? Why are campus sexual assaults on the rise? Do television sitcoms teach us something about the way we relate to each other that isn't true? While tackling these questions, Malcolm Gladwell was not solely writing a book for the page. He was also producing for the ear. In the audiobook version of Talking to Strangers, you'll hear the voices of people he interviewed--scientists, criminologists, military psychologists. Court transcripts are brought to life with re-enactments. You actually hear the contentious arrest of Sandra Bland by the side of the road in Texas. As Gladwell revisits the deceptions of Bernie Madoff, the trial of Amanda Knox, and the suicide of Sylvia Plath, you hear directly from many of the players in these real-life tragedies. There's even a theme song - Janelle Monae's 'Hell You Talmbout.'", author_id=25, genre_id=4)
        book43 = Book(title="The Comfort Book", image="/assets/books/comfort.jpg", genre="Nonfiction", synopsis="The Comfort Book is Haig’s life raft: it’s a collection of notes, lists, and stories written over a span of several years that originally served as gentle reminders to Haig’s future self that things are not always as dark as they may seem. Incorporating a diverse array of sources from across the world, history, science, and his own experiences, Haig offers warmth and reassurance, reminding us to slow down and appreciate the beauty and unpredictability of existence.", author_id=17, genre_id=4)
        book44 = Book(title="An Unfinished Love Story", image="/assets/books/unfinished.jpg", genre="Nonfiction", synopsis="Dick and Doris Goodwin were married for forty-two years and married to American history even longer. In his twenties, Dick was one of the brilliant young men of John F. Kennedy’s New Frontier. In his thirties he both named and helped design Lyndon Johnson’s Great Society and was a speechwriter and close advisor to Robert Kennedy. Doris Kearns was a twenty-four-year-old graduate student when selected as a White House Fellow. She worked directly for Lyndon Johnson and later assisted on his memoir.", author_id=26, genre_id=4)
        book45 = Book(title="The Maniac", image="/assets/books/maniac.jpg", genre="Nonfiction", synopsis="The MANIAC places von Neumann at the center of a literary triptych that begins with Paul Ehrenfest, an Austrian physicist and friend of Einstein, who fell into despair when he saw science and technology become tyrannical forces; it ends a hundred years later, in the showdown between the South Korean Go Master Lee Sedol and the AI program AlphaGo, an encounter embodying the central question of von Neumann's most ambitious unfinished project: the creation of a self-reproducing machine, an intelligence able to evolve beyond human understanding or control. A work of beauty and fabulous momentum, The MANIAC confronts us with the deepest questions we face as a species.", author_id=27, genre_id=4)
        

        rating_review_mapping = {
            1: ["Disappointed, expected more from this author.", "Too predictable, didn't enjoy it much.👎", "Wording was weird, wouldn't recommend.", "Probably one of the worst books i have ever read."],
            2: ["Expected more, but still an okay read.", "Not the best, but had some good moments.", "Based off other books, i expected this to be better 😕"],
            3: ["A decent book, had its ups and downs.", "Good story, but could have been better.", "The ending could have been better, but okay book.", ],
            4: ["Enjoyed it, would recommend to others.", "Captivating plot, kept me hooked till the end.", "Some confusing parts, but would recommend."],
            5: ["Amazing book, couldn't put it down!", "A must-read!", "The characters were so relatable.", "SO SO SO GOOD!", "well worth reading."]
        }

        
        def generate_reviews_from_array(num_reviews):
            reviews = []
            for _ in range(num_reviews):
                rating = randint(1, 5)
                review_text = rc(rating_review_mapping[rating])
                reviews.append(Review(rating=rating, text=review_text))
            return reviews

        
        book1.reviews = generate_reviews_from_array(5)
        book2.reviews = generate_reviews_from_array(3)
        book3.reviews = generate_reviews_from_array(4)
        book4.reviews = generate_reviews_from_array(6)
        book5.reviews = generate_reviews_from_array(4)
        book6.reviews = generate_reviews_from_array(11)
        book7.reviews = generate_reviews_from_array(3)
        book8.reviews = generate_reviews_from_array(1)
        book9.reviews = generate_reviews_from_array(18)
        book10.reviews = generate_reviews_from_array(5)
        book11.reviews = generate_reviews_from_array(4)
        book12.reviews = generate_reviews_from_array(2)
        book13.reviews = generate_reviews_from_array(8)
        book14.reviews = generate_reviews_from_array(8)
        book15.reviews = generate_reviews_from_array(8)
        book17.reviews = generate_reviews_from_array(8)
        book18.reviews = generate_reviews_from_array(8)
        book19.reviews = generate_reviews_from_array(8)
        book20.reviews = generate_reviews_from_array(8)
        book21.reviews = generate_reviews_from_array(8)
        book22.reviews = generate_reviews_from_array(8)
        book23.reviews = generate_reviews_from_array(8)
        book24.reviews = generate_reviews_from_array(8)
        book25.reviews = generate_reviews_from_array(8)
        book26.reviews = generate_reviews_from_array(8)
        book27.reviews = generate_reviews_from_array(8)
        book28.reviews = generate_reviews_from_array(8)
        book29.reviews = generate_reviews_from_array(8)
        book30.reviews = generate_reviews_from_array(8)
        book31.reviews = generate_reviews_from_array(8)
        book32.reviews = generate_reviews_from_array(8)
        book33.reviews = generate_reviews_from_array(8)
        book34.reviews = generate_reviews_from_array(8)
        book35.reviews = generate_reviews_from_array(8)
        book36.reviews = generate_reviews_from_array(8)
        book37.reviews = generate_reviews_from_array(8)
        book38.reviews = generate_reviews_from_array(8)
        book39.reviews = generate_reviews_from_array(8)
        book40.reviews = generate_reviews_from_array(8)
        book41.reviews = generate_reviews_from_array(8)
        book42.reviews = generate_reviews_from_array(8)
        book43.reviews = generate_reviews_from_array(8)
        book44.reviews = generate_reviews_from_array(8)
        book45.reviews = generate_reviews_from_array(8)

        


        db.session.add_all([book1, book2, book3, book4, book5, book6, book7, book8, book9, book10, book11, book12, book13, book14, book15, book16, book17, book18, book19, book20, book21, book22, book23, book24, book25, book26, book27, book28, book29, book30, book31, book32, book33, book34, book35, book36, book37, book38, book39, book40, book41, book42, book43, book44, book45])
        db.session.commit()

        review1 = Review(rating=4, text="INITIAL REACTION: WILL UPDATE WITH REVIEW LATER BUT KNOW I LOVED THIS. IT KILLED ME AND BROUGHT ME BACK TO LIFE Y'ALL.", book_id=3)
        review2 = Review(rating=2, text="I cannot remember ever being this conflicted over a book. There are parts of A Court of Thorns and Roses I really loved, but a lot of parts I really hated", book_id=3)
        review3 = Review(rating=5, text="I'm speechless. What am I supposed to say after this?", book_id=3)
         
        db.session.add_all([review1, review2, review3])
        db.session.commit()

        print("Completed seeding!")
