""" revert

Revision ID: 0a56f6086798
Revises: bcbb084f6633
Create Date: 2024-04-29 09:37:36.980689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a56f6086798'
down_revision = 'bcbb084f6633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_books_author_id_authors', type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_books_author_id_authors', 'authors', ['author_id'], ['id'])

    # ### end Alembic commands ###
