"""update relationship

Revision ID: 31eaf52a7aaa
Revises: 5385d7b9ebeb
Create Date: 2024-05-03 12:03:30.734271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31eaf52a7aaa'
down_revision = '5385d7b9ebeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_books_author_id_authors', type_='foreignkey')
        batch_op.drop_column('genre')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(), nullable=False))
        batch_op.create_foreign_key('fk_books_author_id_authors', 'authors', ['author_id'], ['id'])

    # ### end Alembic commands ###
