"""update read an tbread table

Revision ID: 3fc364929686
Revises: 0a56f6086798
Create Date: 2024-04-29 15:24:35.444360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc364929686'
down_revision = '0a56f6086798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_constraint('fk_authors_book_id_books', type_='foreignkey')
        batch_op.drop_column('book_id')

    with op.batch_alter_table('reads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.Boolean(), nullable=True))

    with op.batch_alter_table('tbreads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbreads', schema=None) as batch_op:
        batch_op.drop_column('favorite')

    with op.batch_alter_table('reads', schema=None) as batch_op:
        batch_op.drop_column('favorite')

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_authors_book_id_books', 'books', ['book_id'], ['id'])

    # ### end Alembic commands ###
