"""update tables

Revision ID: 80cb51d306ba
Revises: 96ac42032a13
Create Date: 2024-04-28 19:05:07.568800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80cb51d306ba'
down_revision = '96ac42032a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_books_genre_id_genres'), 'genres', ['genre_id'], ['id'])

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_constraint('fk_genres_book_id_books', type_='foreignkey')
        batch_op.drop_column('book_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_genres_book_id_books', 'books', ['book_id'], ['id'])

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_books_genre_id_genres'), type_='foreignkey')
        batch_op.drop_column('genre_id')

    # ### end Alembic commands ###
