"""update relationships

Revision ID: 96ac42032a13
Revises: c953b5e71909
Create Date: 2024-04-25 14:38:01.940356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96ac42032a13'
down_revision = 'c953b5e71909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(), nullable=False))
        batch_op.drop_constraint('fk_books_genre_id_genres', type_='foreignkey')
        batch_op.drop_column('genre_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_books_genre_id_genres', 'genres', ['genre_id'], ['id'])
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
