"""add favorite column

Revision ID: b480cc53025a
Revises: 172b1ac45eb4
Create Date: 2024-04-29 15:44:24.780625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b480cc53025a'
down_revision = '172b1ac45eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.Boolean(), nullable=True))

    with op.batch_alter_table('tbreads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbreads', schema=None) as batch_op:
        batch_op.drop_column('favorite')

    with op.batch_alter_table('reads', schema=None) as batch_op:
        batch_op.drop_column('favorite')

    # ### end Alembic commands ###
