"""implement author relationship

Revision ID: bcbb084f6633
Revises: 80cb51d306ba
Create Date: 2024-04-29 09:34:23.920104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcbb084f6633'
down_revision = '80cb51d306ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_authors_book_id_books'), 'books', ['book_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_authors_book_id_books'), type_='foreignkey')
        batch_op.drop_column('book_id')

    # ### end Alembic commands ###
